site_name: Gazelle Plugin

repo_name: 'Fork on GitHub '
repo_url: "https://github.com/oap-project/gazelle_plugin.git"
edit_uri: ""


nav:
  - User Guide: User-Guide.md
  - Prerequisite: Prerequisite.md
  - Installation: Installation.md
  - InstallationNotes: InstallationNotes.md
  - Configuration: Configuration.md
  - SparkInstallation: SparkInstallation.md
  - ApacheArrowInstallation: ApacheArrowInstallation.md
  - Columnar UDF Development: Columnar-UDF-Development-Guide.md
  - Memory Allocation in Gazelle Plugin: memory.md
  - Performance Tuning for Gazelle Plugin: performance.md
  - OAP Installation Guide: OAP-Installation-Guide.md
  - OAP Developer Guide: OAP-Developer-Guide.md
  - Version Selector: "../"



theme: readthedocs


plugins:
  - search
  - mkdocs-versioning:
      version: 1.5.0
      exclude_from_nav: ["image", "js", "css", "fonts", "img"]
