/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_ml_clustering_KMeansDALImpl */

#ifndef _Included_org_apache_spark_ml_clustering_KMeansDALImpl
#define _Included_org_apache_spark_ml_clustering_KMeansDALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_ml_clustering_KMeansDALImpl
 * Method:    cKMeansDALComputeWithInitCenters
 * Signature: (JJIDIIILorg/apache/spark/ml/clustering/KMeansResult;)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_spark_ml_clustering_KMeansDALImpl_cKMeansDALComputeWithInitCenters
  (JNIEnv *, jobject, jlong, jlong, jint, jdouble, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
