/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_ml_feature_PCADALImpl */

#ifndef _Included_org_apache_spark_ml_feature_PCADALImpl
#define _Included_org_apache_spark_ml_feature_PCADALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_ml_feature_PCADALImpl
 * Method:    cPCATrainDAL
 * Signature: (JIIILorg/apache/spark/ml/feature/PCAResult;)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_spark_ml_feature_PCADALImpl_cPCATrainDAL
  (JNIEnv *, jobject, jlong, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
