/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_ml_util_OneDAL__ */

#ifndef _Included_org_apache_spark_ml_util_OneDAL__
#define _Included_org_apache_spark_ml_util_OneDAL__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_ml_util_OneDAL__
 * Method:    setNumericTableValue
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_org_apache_spark_ml_util_OneDAL_00024_setNumericTableValue
  (JNIEnv *, jobject, jlong, jint, jint, jdouble);

JNIEXPORT void JNICALL Java_org_apache_spark_ml_util_OneDAL_00024_cSetDoubleBatch
  (JNIEnv *env, jobject, jlong numTableAddr, jint curRows, jdoubleArray batch, jint numRows, jint numCols);

JNIEXPORT void JNICALL Java_org_apache_spark_ml_util_OneDAL_00024_cSetDoubleIterator
  (JNIEnv *env, jobject,jlong numTableAddr, jobject jiter, jint curRows);

JNIEXPORT void JNICALL Java_org_apache_spark_ml_util_OneDAL_00024_cAddNumericTable
	  (JNIEnv *, jobject, jlong, jlong);

JNIEXPORT void JNICALL Java_org_apache_spark_ml_util_OneDAL_00024_cFreeDataMemory
          (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
