/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_oap_common_unsafe_PersistentMemoryPlatform */

#ifndef _Included_com_intel_oap_common_unsafe_PersistentMemoryPlatform
#define _Included_com_intel_oap_common_unsafe_PersistentMemoryPlatform
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_intel_oap_common_unsafe_PersistentMemoryPlatform
 * Method:    initializeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_oap_common_unsafe_PersistentMemoryPlatform_initializeKmem
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_oap_common_unsafe_PersistentMemoryPlatform
 * Method:    initializeNative
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_intel_oap_common_unsafe_PersistentMemoryPlatform_initializeNative
  (JNIEnv *, jclass, jstring, jlong, jint);

/*
 * Class:     com_intel_oap_common_unsafe_PersistentMemoryPlatform
 * Method:    setNUMANode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_oap_common_unsafe_PersistentMemoryPlatform_setNUMANode
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_intel_oap_common_unsafe_PersistentMemoryPlatform
 * Method:    allocateMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oap_common_unsafe_PersistentMemoryPlatform_allocateVolatileMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_oap_common_unsafe_PersistentMemoryPlatform
 * Method:    getOccupiedSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_oap_common_unsafe_PersistentMemoryPlatform_getOccupiedSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_oap_common_unsafe_PersistentMemoryPlatform
 * Method:    freeMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_oap_common_unsafe_PersistentMemoryPlatform_freeMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_oap_common_unsafe_PersistentMemoryPlatform
 * Method:    copyMemory
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_oap_common_unsafe_PersistentMemoryPlatform_copyMemory
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
