# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Dev Cron

on:
  push:
    paths:
      - '.github/workflows/dev_cron.yml'
  pull_request:
    paths:
      - '.github/workflows/dev_cron.yml'
  schedule:
    - cron: |
        */15 * * * *

jobs:

  issues-link:
    if: github.repository == 'oap-project/native-sql-egnine'
    name: issues link
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Comment
        uses: actions/github-script@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs");
            const path = ".github/workflows/dev_cron/issues_link.js";
            const script = fs.readFileSync(path).toString();
            eval(script);

  title-check:
    if: github.repository == 'oap-project/native-sql-engine'
    name: Title check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check
        uses: actions/github-script@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs");
            const path = ".github/workflows/dev_cron/title_check.js";
            const script = fs.readFileSync(path).toString();
            eval(script);
